# -*- coding: utf-8 -*-
"""Task3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14fobk_W-wfRn0O4IlgA4ueWR5vjpgTqr
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report
import zipfile
import urllib.request

# Download the ZIP file
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/00222/bank-additional.zip"
zip_path, _ = urllib.request.urlretrieve(url)

# Extract the CSV file from the ZIP archive
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall()

# Load the Dataset
bank_data = pd.read_csv("bank-additional/bank-additional-full.csv", sep=';')

# Check data types
print(bank_data.dtypes)

# Data Preprocessing
X = bank_data.drop(columns=['y'])
y = (bank_data['y'] == 'yes').astype(int)  # Convert target variable to binary
X = pd.get_dummies(X)

# Split the Data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Build the Decision Tree Classifier
clf = DecisionTreeClassifier(max_depth=5, random_state=42)

# Train the Model
clf.fit(X_train, y_train)

# Evaluate the Model
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("Classification Report:")
print(report)